### ISSUE TITLE
Document limitations of the deep_merge mode in the Triggering builds doc

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1485] opened 2017-10-05 11:31 UTC
https://docs.travis-ci.com/user/triggering-builds/#Customizing-the-build-configuration

The `deep_merge` feature only works at the moment with the YAML format for associative arrays (`KEY: VALUE`) instead of lists (`- STRING`). This restriction is currently tied to the way we internally process the deep_merge process of the hashes in the configuration (using Active Support's deep_merge).

The current documentation is leading to confusion, since people will see that, when using lists, their options will be replaced instead of merged.

**Comment by chris-ratcliffe** [comment] 2017-12-14 14:18
@iriberri , can you please give examples here of an existing .travis.yml + api payload that would allow deep merge to work, and oen that won't, just for clarity?  Thanks.

**Comment by iriberri** [comment] 2017-12-14 14:30
Hi @chris-ratcliffe!

Sure - here are some examples:

Consider the following body for the API request:

```
body='{"request": {"config": { "merge_mode": "deep_merge", "env": { "global" : {"BAZ":"baz_from_api_request"}}}}}'
```

**Example - working syntax:**

```
language: node_js

env:
  global:
    FOO: fofo

install: true

script: true
```


**Example -  failing case, with "typical" list syntax**:

```
language: node_js

env:
  global:
    - FOO=fofo

install: true

script: true
```

Does this help?

**Comment by chris-ratcliffe** [comment] 2017-12-14 16:31
Thanks @iriberri.  Yes, that works fine if the .travis.yml and the api payload both use the same scope for the environment variables.  (global or not global)  I noticed though that if the api payload contains only global environment variables, and the .travis.yml has non-global environment variables, or vice-versa, then they aren't merged.  It would appear that in both situations, if global is used in either location, the non-global settings are completely ignored.  Is that working as designed?

**Comment by cben** [comment] 2018-02-19 22:45
The ability to write `FOO: fofo` mapping instead of `- FOO=fofo` list is not even mentioned on https://docs.travis-ci.com/user/environment-variables/.

**Comment by BanzaiMan** [comment] 2018-02-21 10:02
@cben Yes, we would look at fixing that as well.

**Comment by cben** [comment] 2018-02-27 12:36
Ooh, if the behavior of `env: {NAME: value}` is still undefined, any chance to define it as literal values not needing shell quoting? Wrote longer motivation on https://github.com/travis-ci/travis-ci/issues/1446#issuecomment-368859313

**Comment by cben** [comment] 2018-08-27 04:37
Still relevant.  docs don't mention hash form, only list form that doesnt work with deep_merge.

**Comment by rudysuharyadi** [comment] 2019-02-12 04:47
i dont get it. using this

`env:
  global:
    FOO: fofo`

is not working. It have been a year already, is there any update on this?

**Comment by Bethronding** [comment] 2019-02-14 19:22
List form still doesn't work with deep_merge and creds in global env with syntax of `secure: ` can only be written in string format, this now brings up compatibility issue. Is there a ETA of this getting fixed?

**Comment by rudysuharyadi** [comment] 2019-02-15 17:13
Just contact their support yesterday, still not fixed, no ETA, and no way around.

**Comment by PARADOXST** [comment] 2019-05-03 00:31
However, if you have `secure` var defined in `.travis.yml` under `env.global`, the workaround does not seem to work...

Any thoughts?

**Comment by rudysuharyadi** [comment] 2019-05-03 04:09
You can go to travis repo setting, and add secure env variable there. You can also use export in before script section. Just dont use env.global.

**Comment by PARADOXST** [comment] 2019-05-03 04:18
@rudysuharyadi thanks for the suggestion. For you second suggestion, if I put encrypted vars in the script, is there a way I can decrypt it?

**Comment by rudysuharyadi** [comment] 2019-05-03 04:29
export in the script cannot be used for encrypted variable by travis. I use this export in before script section because mine is dynamic variable.

**Comment by PARADOXST** [comment] 2019-05-03 18:25
@rudysuharyadi I see. Also I tried add secure vars in repo settings, it seems travis only recognizes it only as an unencrypted var named `secure`. Is there anything I am missing?

**Comment by rudysuharyadi** [comment] 2019-05-04 05:47
Hi @PARADOXST, there is a documentation for that one here https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings.

**Comment by seb4stien** [comment] 2019-08-21 17:56
Another workaround for secure variables is to use the command line and to store the variables in an encrypted file with "travis encrypt-file".

**Comment by lbergelson** [comment] 2019-11-18 22:51
This is confusing me as well.  Is there a solution for deep_merging lists yet?  I want to add an additional step to the `before_install` phase using an api request but it replaces it instead.  

ex:
```
body='{
  "request": {
    "config": {
      "merge_mode": "deep_merge",
      "before_install": "echo systemProp.htsjdk.version=1.2>> gradle.properties"
    },
    "branch":"master",
  }
}'
```

Is there a way to do this?

**Comment by svenfuchs** [comment] 2019-11-19 15:46
@lbergelson this should be possible now when the feature "Build Config Validation" is enabled https://docs.travis-ci.com/user/build-config-validation. this uses a new parser for your build configuration that comes with two new merge modes `deep_merge_append` and `deep_merge_prepend`, with `deep_merge_append` being the new default mode (if none was specified).

as for the env var limitations discussed in this issue, those go away with this feature as well. the new parser normalizes all env vars into hashes, so these two examples from above result in the same configuration:

```yaml
env:
  global:
    FOO: fofo

env:
  global:
    - FOO=fofo
```

**Comment by lbergelson** [comment] 2019-11-19 21:29
@svenfuchs Thank you, that sounds just like what I need.

**Closed** 2019-11-27 05:44 UTC
Labels: WIP, docs
