### ISSUE TITLE
Some example don't verify on http://lint.travis-ci.org

### ISSUE THREAD

**Issue by hamogu** [travis-ci/docs-travis-ci-com#491] opened 2016-01-25 01:22 UTC
E.g. an example on 
https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure
```
addons:
  apt:
    packages:
    - cmake
    - time
```
Gives me the following in http://lint.travis-ci.org/:
```
    value for addons section is empty, dropping
    missing key language, defaulting to ruby
    in addons section: unexpected key apt, dropping
```

My best guess is that the linter is set up for the legacy infrastructure and not for the container based infrastructure.
I don't know where to report that though.
In the meantime, I suggest a warning in the docs like ".travis.yml for the container based infrastructure can currently not be validated through lint.tracivs-ci.org."

**Comment by BanzaiMan** [comment] 2016-01-25 01:40
Closing as a duplicate of https://github.com/travis-ci/travis-yaml/issues/58. This is not really a docs issue, but a tools one.

**Closed by BanzaiMan** 2016-01-25 01:40 UTC
