### ISSUE TITLE
Up to date list of available Erlang versions

### ISSUE THREAD

**Issue by eproxus** [travis-ci/docs-travis-ci-com#225] opened 2015-04-08 08:09 UTC
Where can I find an up to date list of available Erlang versions on travis-ci.org and travis-ci.com? 

The docs pages lists just two of the available versions and not even the latest one:
http://docs.travis-ci.com/user/languages/erlang/

The cookbooks contains a list, but for example 17.5 is in this list but not available on travis-ci.org:
https://github.com/travis-ci/travis-cookbooks/blob/4285438264dac78378960f97186f06693bcab0ff/ci_environment/kerl/attributes/source.rb

It would be nice if there was a canonical list somewhere which definitely lists all available versions that are actually installed. It is very tedious to have to commit new `.travis.yml` files all the time just to guess which versions are available. It also creates ugly commit and build histories.

**Comment by BanzaiMan** [comment] 2015-04-08 19:17
The documentation is not meant to be a completely up-to-date documentation of what is available. Often the reality drifts away from the documentation. This is one such case.

We have a fold inside the build log that *should* have this information, but it, too, was broken for the most recent build images. This should change with the next update (tomorrow).

If you want to really look for the cookbooks version that was used to produce the build you are running tests on, look inside the "Build system information" fold for it (e.g., https://travis-ci.org/travis-ci/travis-build/builds/57673806#L15).

**Comment by eproxus** [comment] 2015-04-09 07:53
Do you mean Erlang versions were missing from the `Build system information` fold? Or that there should be another fold listing all available versions?

Perhaps this fold should then be mentioned in the documentation for each language. I have often tried to figure out which versions were available and searching for Travis + Erlang only yields the document I linked to above.

**Comment by whip112** [comment] 2015-04-29 06:41
Update.

**Comment by linearregression** [comment] 2015-06-02 19:43
It looks like the latest erlang releases are always missing from the official releases.
The receipes need to do a 'kerl update releases to pull down the latest from erlang.org
 kerl update releases 

You can run 
kerl list releases   to see what your local kerl knows. 

PS: 'kerl update releases' pull from erlang.org, so there may be some work to do to skip this if already present locally.

**Comment by eproxus** [comment] 2015-06-09 10:02
The fold still doesn't contain the available Erlang versions. The cookbooks doesn't really tell me which Erlang versions are installed. At least I can't find any list of Erlang versions in there.

**Comment by plaindocs** [comment] 2017-03-20 08:45
We're working on a better way of managing version information in the docs.

> Get a complete list of the pre-compiled versions available on the VM by adding kerl list installations to the before_script: section of your .travis.yml. Note that this list does not include releases which are downloaded on demand, such as 18.1 .

Covers the basics, so I'm closing this for now.

**Closed by plaindocs** 2017-03-20 08:45 UTC
Labels: docs, needs-test-jobs, version-update

**Comment by beenotung** [comment] 2017-12-09 16:16
@linearregression how can I set a hook to run `kerl update releases` before travis run wget?

Tried to put in before_install but it seems too late.

**Comment by BanzaiMan** [comment] 2017-12-10 22:27
@beenotung `kerl` does not come into play. We take what is given in the config and look for the pre-compiled archive. If the archive exists, your build will use it and proceed. If it doesn't, it fails.

**Comment by beenotung** [comment] 2017-12-24 16:35
so if I really want to use a version that's not available, I may better off writing custom script to do the setup?

**Comment by alecernas** [comment] 2023-02-02 00:16
I have the same question, if my erlang version is not available what steps I need to follow? can't find anything in the docs
